"use server"

import { randomBytes } from "node:crypto"
import { createAdminClient } from "@/lib/supabase/admin"
import { assertPermission } from "@/lib/auth/permissions"
import { logActivity } from "@/lib/data/audit"
import type { Database } from "@/lib/database.types"
import type { AdminUser, UIRole, UIStatus, UserInput } from "@/lib/data/users.types"

type DbRole = Database["public"]["Enums"]["user_role"]

// Roles surfaced in the admin User Management screen (sponsors/parents are
// managed elsewhere).
const MANAGED_DB_ROLES: DbRole[] = [
  "super_admin",
  "admin",
  "manager",
  "mentor",
  "student",
]

const DB_TO_UI_ROLE: Record<string, UIRole> = {
  super_admin: "Admin",
  admin: "Admin",
  manager: "Manager",
  mentor: "Mentor",
  student: "Student",
}
const UI_TO_DB_ROLE: Record<UIRole, DbRole> = {
  Admin: "admin",
  Manager: "manager",
  Mentor: "mentor",
  Student: "student",
}

function uiStatusToDb(s: UIStatus) {
  return s === "Suspended" ? ("suspended" as const) : ("active" as const)
}

function generatePassword() {
  // 12+ chars, mixed — comfortably above Supabase's minimum.
  return "Aa1" + randomBytes(9).toString("base64url")
}

export async function listUsers(): Promise<AdminUser[]> {
  await assertPermission("users.view")
  const admin = createAdminClient()

  const { data, error } = await admin
    .from("profiles")
    .select("id, full_name, email, phone, role, status, last_login_at, created_at")
    .in("role", MANAGED_DB_ROLES)
    .order("created_at", { ascending: false })

  if (error) throw new Error(error.message)

  return (data ?? []).map((p) => ({
    id: p.id,
    name: p.full_name ?? "",
    email: p.email ?? "",
    phone: p.phone ?? "",
    role: DB_TO_UI_ROLE[p.role] ?? "Student",
    status: p.status === "suspended" ? "Suspended" : "Active",
    lastLogin: p.last_login_at
      ? new Date(p.last_login_at).toLocaleString()
      : "—",
    createdAt: p.created_at ? new Date(p.created_at).toLocaleDateString() : "",
  }))
}

export async function createUser(
  input: UserInput,
): Promise<{ tempPassword?: string; error?: string }> {
  let me
  try {
    me = await assertPermission("users.manage")
  } catch (e) {
    return { error: (e as Error).message }
  }
  const admin = createAdminClient()

  const autoGenerated = !input.password?.trim()
  const password = input.password?.trim() || generatePassword()
  const dbRole = UI_TO_DB_ROLE[input.role]

  const { data, error } = await admin.auth.admin.createUser({
    email: input.email.trim(),
    password,
    email_confirm: true,
    user_metadata: { full_name: input.name.trim(), role: dbRole },
  })
  if (error || !data.user) {
    return { error: error?.message ?? "Failed to create user." }
  }

  // The handle_new_user trigger already inserted the profile; fill the rest.
  const { error: pErr } = await admin
    .from("profiles")
    .update({
      full_name: input.name.trim(),
      phone: input.phone.trim(),
      role: dbRole,
      status: uiStatusToDb(input.status),
    })
    .eq("id", data.user.id)
  if (pErr) return { error: pErr.message }

  await logActivity({ actorId: me.userId, action: "Created user", targetType: "user", targetId: data.user.id, description: `${input.name.trim()} (${input.role})` }, admin)
  return { tempPassword: autoGenerated ? password : undefined }
}

export async function updateUser(
  id: string,
  input: Omit<UserInput, "password">,
): Promise<{ error?: string }> {
  let me
  try {
    me = await assertPermission("users.manage")
  } catch (e) {
    return { error: (e as Error).message }
  }
  const admin = createAdminClient()

  const { data: current } = await admin
    .from("profiles")
    .select("role, email")
    .eq("id", id)
    .single()

  // Never silently downgrade a super_admin to admin via the "Admin" option.
  let dbRole = UI_TO_DB_ROLE[input.role]
  if (current?.role === "super_admin" && input.role === "Admin") {
    dbRole = "super_admin"
  }

  const newEmail = input.email.trim()
  if (current && newEmail && newEmail !== current.email) {
    const { error } = await admin.auth.admin.updateUserById(id, {
      email: newEmail,
      email_confirm: true,
    })
    if (error) return { error: error.message }
  }

  const { error } = await admin
    .from("profiles")
    .update({
      full_name: input.name.trim(),
      email: newEmail,
      phone: input.phone.trim(),
      role: dbRole,
      status: uiStatusToDb(input.status),
    })
    .eq("id", id)
  if (error) return { error: error.message }

  await logActivity({ actorId: me.userId, action: "Updated user", targetType: "user", targetId: id, description: input.name.trim() }, admin)
  return {}
}

export async function deleteUser(id: string): Promise<{ error?: string }> {
  let me
  try {
    me = await assertPermission("users.manage")
  } catch (e) {
    return { error: (e as Error).message }
  }
  if (id === me.userId) {
    return { error: "You cannot delete your own account." }
  }

  const admin = createAdminClient()
  const { data: victim } = await admin.from("profiles").select("full_name").eq("id", id).single()
  // Cascades to public.profiles via the FK on delete cascade.
  const { error } = await admin.auth.admin.deleteUser(id)
  if (error) return { error: error.message }

  await logActivity({ actorId: me.userId, action: "Deleted user", targetType: "user", targetId: id, description: victim?.full_name ?? undefined }, admin)
  return {}
}
